CREATE TABLE "reversos_consumo" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consumo_original_id" integer NOT NULL,
  "cantidad" decimal(12,2) NOT NULL,
  "costo_unitario" decimal(12,2) NOT NULL,
  "subtotal" decimal(12,2) NOT NULL,
  "motivo" text NOT NULL,
  "autorizado_por_id" integer NOT NULL,
  "clave_idempotencia" uuid NOT NULL,
  "fecha_reverso" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ck_reverso_valores" CHECK (
    "cantidad" > 0 AND "costo_unitario" >= 0 AND "subtotal" >= 0 AND btrim("motivo") <> ''
  ),
  CONSTRAINT "reversos_consumo_consumo_original_id_fkey" FOREIGN KEY ("consumo_original_id")
    REFERENCES "consumos_repuesto"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "reversos_consumo_autorizado_por_id_fkey" FOREIGN KEY ("autorizado_por_id")
    REFERENCES "usuarios"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "reversos_consumo_clave_idempotencia_key" ON "reversos_consumo"("clave_idempotencia");
CREATE INDEX "reversos_consumo_consumo_original_id_fecha_reverso_idx" ON "reversos_consumo"("consumo_original_id", "fecha_reverso");
CREATE INDEX "reversos_consumo_autorizado_por_id_idx" ON "reversos_consumo"("autorizado_por_id");

ALTER TABLE "movimientos_inventario" ADD COLUMN "reverso_consumo_id" integer;
CREATE UNIQUE INDEX "movimientos_inventario_reverso_consumo_id_key" ON "movimientos_inventario"("reverso_consumo_id");
ALTER TABLE "movimientos_inventario" ADD CONSTRAINT "movimientos_inventario_reverso_consumo_id_fkey"
  FOREIGN KEY ("reverso_consumo_id") REFERENCES "reversos_consumo"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "movimientos_inventario" DROP CONSTRAINT "ck_movimientos_inventario_consumo";
ALTER TABLE "movimientos_inventario" ADD CONSTRAINT "ck_movimientos_inventario_consumo" CHECK (
  ("tipo" = 'CONSUMO' AND "consumo_repuesto_id" IS NOT NULL AND "reverso_consumo_id" IS NULL)
  OR ("tipo" = 'REVERSO_CONSUMO' AND "consumo_repuesto_id" IS NULL AND "reverso_consumo_id" IS NOT NULL)
  OR ("tipo" NOT IN ('CONSUMO', 'REVERSO_CONSUMO') AND "consumo_repuesto_id" IS NULL AND "reverso_consumo_id" IS NULL)
);

CREATE FUNCTION "fn_validar_reverso_consumo"()
RETURNS trigger LANGUAGE plpgsql SET search_path = public, pg_temp AS $$
DECLARE
  original "consumos_repuesto"%ROWTYPE;
  cantidad_previa decimal(12,2);
  subtotal_previo decimal(12,2);
BEGIN
  SELECT * INTO original FROM "consumos_repuesto"
    WHERE "id" = NEW."consumo_original_id" FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Consumo original no encontrado'; END IF;
  SELECT COALESCE(sum("cantidad"), 0), COALESCE(sum("subtotal"), 0)
    INTO cantidad_previa, subtotal_previo
    FROM "reversos_consumo"
    WHERE "consumo_original_id" = NEW."consumo_original_id" AND "id" <> NEW."id";
  IF NEW."cantidad" + cantidad_previa > original."cantidad"
    OR NEW."subtotal" + subtotal_previo > original."subtotal"
    OR NEW."costo_unitario" <> original."costo_unitario" THEN
    RAISE EXCEPTION 'Reverso supera cantidad/costo original o altera snapshot';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER "trg_validar_reverso_consumo" BEFORE INSERT OR UPDATE ON "reversos_consumo"
  FOR EACH ROW EXECUTE FUNCTION "fn_validar_reverso_consumo"();

CREATE FUNCTION "fn_assert_reverso_movimiento_unico"()
RETURNS trigger LANGUAGE plpgsql SET search_path = public, pg_temp AS $$
DECLARE
  reverso_id integer;
  reverso_ids integer[];
  movimientos integer;
BEGIN
  IF TG_TABLE_NAME = 'reversos_consumo' THEN
    reverso_ids := ARRAY[NEW."id"];
  ELSE
    reverso_ids := ARRAY_REMOVE(ARRAY[
      CASE WHEN TG_OP <> 'INSERT' THEN OLD."reverso_consumo_id" END,
      CASE WHEN TG_OP <> 'DELETE' THEN NEW."reverso_consumo_id" END
    ], NULL);
  END IF;
  FOREACH reverso_id IN ARRAY reverso_ids LOOP
    IF EXISTS (SELECT 1 FROM "reversos_consumo" WHERE "id" = reverso_id) THEN
      SELECT count(*) INTO movimientos
        FROM "movimientos_inventario" m
        JOIN "reversos_consumo" r ON r."id" = m."reverso_consumo_id"
        JOIN "consumos_repuesto" c ON c."id" = r."consumo_original_id"
        WHERE r."id" = reverso_id
          AND m."tipo" = 'REVERSO_CONSUMO'
          AND m."cantidad" = r."cantidad"
          AND m."costo_unitario" = r."costo_unitario"
          AND m."repuesto_id" = c."repuesto_id";
      IF movimientos <> 1 THEN
        RAISE EXCEPTION 'Reverso % debe tener un movimiento inverso coincidente', reverso_id;
      END IF;
    END IF;
  END LOOP;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;
CREATE CONSTRAINT TRIGGER "trg_reverso_movimiento_unico"
  AFTER INSERT OR UPDATE ON "reversos_consumo" DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION "fn_assert_reverso_movimiento_unico"();
CREATE CONSTRAINT TRIGGER "trg_movimiento_reverso_unico"
  AFTER INSERT OR UPDATE OR DELETE ON "movimientos_inventario" DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION "fn_assert_reverso_movimiento_unico"();
