// Fuente consolidada: docs/INVESTIGACION_AMB_SITME_DATOS_Y_SIMULACION_SGMV.md
// No atribuir la convención de circuito completo al AMB.
export const officialAmbRoutes = [
  {
    codigo: '1',
    nombre: 'GALÁN MODELO ESTADIO UIS (INTEGRADA)',
    origen: 'Barrio Galán',
    destino: 'Parque Estación UIS; retorno a Galán',
    longitudKmOficial: 24,
    operador: 'UNITRANSA S.A.',
    semanticaLongitudOficial: 'NO_DETERMINADA',
    semanticaLongitudDemo: 'CIRCUITO_COMPLETO',
    origenSemanticaDemo: 'SIMULADO_SGMV',
    procedencia: {
      origenDato: 'OFICIAL',
      fuente: 'https://www.amb.gov.co/rutas-publico-colectivo-complementario/',
      fechaConsolidacion: '2026-09-11',
      vigencia: 'PARCIALMENTE_CONFIRMADA',
      frecuenciaPicoRaw: '8',
      frecuenciaValleRaw: '12',
      unidadFrecuencia: 'NO_DETERMINADA',
      primerDespacho: '05:00',
      ultimoDespacho: '20:00',
      claseVehiculo: 'Bus / Buseta / Microbús',
      capacidadMinimaOficial: 14,
      capacidadMaximaOficial: 17,
      semanticaCapacidad: 'CONSERVADA_SEGUN_FUENTE; no inferir plazas por bus',
      recorrido: 'GALÁN MODELO ESTADIO UIS (INTEGRADA)',
      observacion: 'Código de ruta no vinculado documentalmente a anexo jurídico individual 2026.',
    },
  },
  {
    codigo: '7',
    nombre: 'LIMONCITO',
    origen: 'Los Cauchos / Estadio Álvaro Gómez Hurtado',
    destino: 'Limoncito–Bucaramanga; circuito',
    longitudKmOficial: 23,
    operador: 'COTRANDER',
    semanticaLongitudOficial: 'NO_DETERMINADA',
    semanticaLongitudDemo: 'CIRCUITO_COMPLETO',
    origenSemanticaDemo: 'SIMULADO_SGMV',
    procedencia: {
      origenDato: 'OFICIAL',
      fuente: 'https://www.amb.gov.co/rutas-publico-colectivo-complementario/',
      fechaConsolidacion: '2026-09-11',
      vigencia: 'PARCIALMENTE_CONFIRMADA',
      frecuenciaPicoRaw: '6',
      frecuenciaValleRaw: '10',
      unidadFrecuencia: 'NO_DETERMINADA',
      primerDespacho: '04:50',
      ultimoDespacho: '20:30',
      claseVehiculo: 'Bus / Buseta / Microbús',
      capacidadMinimaOficial: 14,
      capacidadMaximaOficial: 17,
      semanticaCapacidad: 'CONSERVADA_SEGUN_FUENTE; no inferir plazas por bus',
      recorrido: 'LIMONCITO',
      observacion: 'Código de ruta no vinculado documentalmente a anexo jurídico individual 2026.',
    },
  },
  {
    codigo: '14',
    nombre: 'PUENTE TIERRA – CENTRO – CARRERA 33 – CIUDAD VALENCIA (INTEGRADA)',
    origen: 'Puente Tierra',
    destino: 'Ciudad Valencia; retorno',
    longitudKmOficial: 49,
    operador: 'TRANSCOLOMBIA S.A.',
    semanticaLongitudOficial: 'NO_DETERMINADA',
    semanticaLongitudDemo: 'CIRCUITO_COMPLETO',
    origenSemanticaDemo: 'SIMULADO_SGMV',
    procedencia: {
      origenDato: 'OFICIAL',
      fuente: 'https://www.amb.gov.co/rutas-publico-colectivo-complementario/',
      fechaConsolidacion: '2026-09-11',
      vigencia: 'PARCIALMENTE_CONFIRMADA',
      frecuenciaPicoRaw: '7',
      frecuenciaValleRaw: '12',
      unidadFrecuencia: 'NO_DETERMINADA',
      primerDespacho: '04:40',
      ultimoDespacho: '17:45',
      claseVehiculo: 'Bus / Buseta / Microbús',
      capacidadMinimaOficial: 20,
      capacidadMaximaOficial: 25,
      semanticaCapacidad: 'CONSERVADA_SEGUN_FUENTE; no inferir plazas por bus',
      recorrido: 'PUENTE TIERRA – CENTRO – CARRERA 33 – CIUDAD VALENCIA (INTEGRADA)',
      observacion: 'Código de ruta no vinculado documentalmente a anexo jurídico individual 2026.',
    },
  },
  {
    codigo: '30',
    nombre: 'MIRADOR DE ARENALES – POBLADO – CENTRO – CARRERA 22',
    origen: 'Mirador de Arenales / Ciudadela Nuevo Girón',
    destino: 'Carrera 22, Bucaramanga; retorno',
    longitudKmOficial: 35,
    operador: 'TRANSPORTES GIRÓN S.A.',
    semanticaLongitudOficial: 'NO_DETERMINADA',
    semanticaLongitudDemo: 'CIRCUITO_COMPLETO',
    origenSemanticaDemo: 'SIMULADO_SGMV',
    procedencia: {
      origenDato: 'OFICIAL',
      fuente: 'https://www.amb.gov.co/rutas-publico-colectivo-complementario/',
      fechaConsolidacion: '2026-09-11',
      vigencia: 'PARCIALMENTE_CONFIRMADA',
      frecuenciaPicoRaw: '9',
      frecuenciaValleRaw: '10',
      unidadFrecuencia: 'NO_DETERMINADA',
      primerDespacho: '05:00',
      ultimoDespacho: '23:00',
      claseVehiculo: 'Bus / Buseta / Microbús',
      capacidadMinimaOficial: 20,
      capacidadMaximaOficial: 23,
      semanticaCapacidad: 'CONSERVADA_SEGUN_FUENTE; no inferir plazas por bus',
      recorrido: 'MIRADOR DE ARENALES – POBLADO – CENTRO – CARRERA 22',
      observacion: 'Código de ruta no vinculado documentalmente a anexo jurídico individual 2026.',
    },
  },
  {
    codigo: '37',
    nombre: 'BRISAS DEL CAMPO – RINCÓN – UIS',
    origen: 'Brisas del Campo',
    destino: 'UIS; retorno',
    longitudKmOficial: 36,
    operador: 'METROPOLITANA DE SERVICIOS S.A.',
    semanticaLongitudOficial: 'NO_DETERMINADA',
    semanticaLongitudDemo: 'CIRCUITO_COMPLETO',
    origenSemanticaDemo: 'SIMULADO_SGMV',
    procedencia: {
      origenDato: 'OFICIAL',
      fuente: 'https://www.amb.gov.co/rutas-publico-colectivo-complementario/',
      fechaConsolidacion: '2026-09-11',
      vigencia: 'PARCIALMENTE_CONFIRMADA',
      frecuenciaPicoRaw: '5',
      frecuenciaValleRaw: '8',
      unidadFrecuencia: 'NO_DETERMINADA',
      primerDespacho: '04:40',
      ultimoDespacho: '20:30',
      claseVehiculo: 'Bus / Buseta / Microbús',
      capacidadMinimaOficial: 22,
      capacidadMaximaOficial: 27,
      semanticaCapacidad: 'CONSERVADA_SEGUN_FUENTE; no inferir plazas por bus',
      recorrido: 'BRISAS DEL CAMPO – RINCÓN – UIS',
      observacion: 'Código de ruta no vinculado documentalmente a anexo jurídico individual 2026.',
    },
  },
  {
    codigo: '39',
    nombre: 'BRISAS DEL CAMPO – RINCÓN – REAL DE MINAS – UIS',
    origen: 'Brisas del Campo',
    destino: 'UIS; retorno',
    longitudKmOficial: 38,
    operador: 'ORIENTAL DE TRANSPORTES S.A.',
    semanticaLongitudOficial: 'NO_DETERMINADA',
    semanticaLongitudDemo: 'CIRCUITO_COMPLETO',
    origenSemanticaDemo: 'SIMULADO_SGMV',
    procedencia: {
      origenDato: 'OFICIAL',
      fuente: 'https://www.amb.gov.co/rutas-publico-colectivo-complementario/',
      fechaConsolidacion: '2026-09-11',
      vigencia: 'PARCIALMENTE_CONFIRMADA',
      frecuenciaPicoRaw: '8',
      frecuenciaValleRaw: '10',
      unidadFrecuencia: 'NO_DETERMINADA',
      primerDespacho: '05:00',
      ultimoDespacho: '23:00',
      claseVehiculo: 'Bus / Buseta / Microbús',
      capacidadMinimaOficial: 18,
      capacidadMaximaOficial: 23,
      semanticaCapacidad: 'CONSERVADA_SEGUN_FUENTE; no inferir plazas por bus',
      recorrido: 'BRISAS DEL CAMPO – RINCÓN – REAL DE MINAS – UIS',
      observacion: 'Código de ruta no vinculado documentalmente a anexo jurídico individual 2026.',
    },
  },
  {
    codigo: '40',
    nombre: 'CAMPIÑA – POBLADO – CARRERA 33',
    origen: 'La Campiña',
    destino: 'Carrera 33, Bucaramanga; retorno',
    longitudKmOficial: 36,
    operador: 'COOTRAGAS CTA.',
    semanticaLongitudOficial: 'NO_DETERMINADA',
    semanticaLongitudDemo: 'CIRCUITO_COMPLETO',
    origenSemanticaDemo: 'SIMULADO_SGMV',
    procedencia: {
      origenDato: 'OFICIAL',
      fuente: 'https://www.amb.gov.co/rutas-publico-colectivo-complementario/',
      fechaConsolidacion: '2026-09-11',
      vigencia: 'PARCIALMENTE_CONFIRMADA',
      frecuenciaPicoRaw: '5',
      frecuenciaValleRaw: '10',
      unidadFrecuencia: 'NO_DETERMINADA',
      primerDespacho: '05:00',
      ultimoDespacho: '23:00',
      claseVehiculo: 'Bus / Buseta / Microbús',
      capacidadMinimaOficial: 13,
      capacidadMaximaOficial: 14,
      semanticaCapacidad: 'CONSERVADA_SEGUN_FUENTE; no inferir plazas por bus',
      recorrido: 'CAMPIÑA – POBLADO – CARRERA 33',
      observacion: 'Código de ruta no vinculado documentalmente a anexo jurídico individual 2026.',
    },
  },
  {
    codigo: '41',
    nombre: 'CARACOLÍ – TRANSVERSAL ORIENTAL – HIPINTO – CARRERA 21 – CENTRO',
    origen: 'Caracolí',
    destino: 'Centro de Bucaramanga; retorno',
    longitudKmOficial: 22,
    operador: 'LUSITANIA S.A.',
    semanticaLongitudOficial: 'NO_DETERMINADA',
    semanticaLongitudDemo: 'CIRCUITO_COMPLETO',
    origenSemanticaDemo: 'SIMULADO_SGMV',
    procedencia: {
      origenDato: 'OFICIAL',
      fuente: 'https://www.amb.gov.co/rutas-publico-colectivo-complementario/',
      fechaConsolidacion: '2026-09-11',
      vigencia: 'PARCIALMENTE_CONFIRMADA',
      frecuenciaPicoRaw: '5',
      frecuenciaValleRaw: '10',
      unidadFrecuencia: 'NO_DETERMINADA',
      primerDespacho: '05:00',
      ultimoDespacho: '23:00',
      claseVehiculo: 'Bus / Buseta / Microbús',
      capacidadMinimaOficial: 9,
      capacidadMaximaOficial: 11,
      semanticaCapacidad: 'CONSERVADA_SEGUN_FUENTE; no inferir plazas por bus',
      recorrido: 'CARACOLÍ – TRANSVERSAL ORIENTAL – HIPINTO – CARRERA 21 – CENTRO',
      observacion: 'Código de ruta no vinculado documentalmente a anexo jurídico individual 2026.',
    },
  },
  {
    codigo: '44',
    nombre: 'FLORIDA – TERMINAL – GIRÓN',
    origen: 'Antiguo Matadero de Florida',
    destino: 'Girón / Mirador de Arenales; retorno',
    longitudKmOficial: 43,
    operador: 'TRANSPORTES SAN JUAN S.A.',
    semanticaLongitudOficial: 'NO_DETERMINADA',
    semanticaLongitudDemo: 'CIRCUITO_COMPLETO',
    origenSemanticaDemo: 'SIMULADO_SGMV',
    procedencia: {
      origenDato: 'OFICIAL',
      fuente: 'https://www.amb.gov.co/rutas-publico-colectivo-complementario/',
      fechaConsolidacion: '2026-09-11',
      vigencia: 'PARCIALMENTE_CONFIRMADA',
      frecuenciaPicoRaw: '8',
      frecuenciaValleRaw: '15',
      unidadFrecuencia: 'NO_DETERMINADA',
      primerDespacho: '04:50',
      ultimoDespacho: '19:30',
      claseVehiculo: 'Bus / Buseta / Microbús',
      capacidadMinimaOficial: 16,
      capacidadMaximaOficial: 20,
      semanticaCapacidad: 'CONSERVADA_SEGUN_FUENTE; no inferir plazas por bus',
      recorrido: 'FLORIDA – TERMINAL – GIRÓN',
      observacion: 'Código de ruta no vinculado documentalmente a anexo jurídico individual 2026.',
    },
  },
  {
    codigo: '53',
    nombre: 'NUEVA COLOMBIA – CARRERA 21',
    origen: 'Nueva Colombia – Puerto Nuevo, Piedecuesta',
    destino: 'Carrera 21 / Parque San Francisco, Bucaramanga; retorno',
    longitudKmOficial: 47,
    operador: 'TRANSPORTES PIEDECUESTA S.A.',
    semanticaLongitudOficial: 'NO_DETERMINADA',
    semanticaLongitudDemo: 'CIRCUITO_COMPLETO',
    origenSemanticaDemo: 'SIMULADO_SGMV',
    procedencia: {
      origenDato: 'OFICIAL',
      fuente: 'https://www.amb.gov.co/rutas-publico-colectivo-complementario/',
      fechaConsolidacion: '2026-09-11',
      vigencia: 'PARCIALMENTE_CONFIRMADA',
      frecuenciaPicoRaw: '10',
      frecuenciaValleRaw: '15',
      unidadFrecuencia: 'NO_DETERMINADA',
      primerDespacho: '05:00',
      ultimoDespacho: '19:00',
      claseVehiculo: 'Bus / Buseta / Microbús',
      capacidadMinimaOficial: 17,
      capacidadMaximaOficial: 21,
      semanticaCapacidad: 'CONSERVADA_SEGUN_FUENTE; no inferir plazas por bus',
      recorrido: 'NUEVA COLOMBIA – CARRERA 21',
      observacion: 'Código de ruta no vinculado documentalmente a anexo jurídico individual 2026.',
    },
  },
  {
    codigo: '55',
    nombre: 'INTRA – MOLINO – CENTRO – QUINTA GRANADA – ESPAÑOLITA',
    origen: 'INTRA, Piedecuesta',
    destino: 'Españolita / Quinta Granada; circuito',
    longitudKmOficial: 15,
    operador: 'TRANSPORTES VILLA DE SAN CARLOS S.A.',
    semanticaLongitudOficial: 'NO_DETERMINADA',
    semanticaLongitudDemo: 'CIRCUITO_COMPLETO',
    origenSemanticaDemo: 'SIMULADO_SGMV',
    procedencia: {
      origenDato: 'OFICIAL',
      fuente: 'https://www.amb.gov.co/rutas-publico-colectivo-complementario/',
      fechaConsolidacion: '2026-09-11',
      vigencia: 'PARCIALMENTE_CONFIRMADA',
      frecuenciaPicoRaw: '9',
      frecuenciaValleRaw: '12',
      unidadFrecuencia: 'NO_DETERMINADA',
      primerDespacho: '04:20',
      ultimoDespacho: '19:00',
      claseVehiculo: 'Bus / Buseta / Microbús',
      capacidadMinimaOficial: 0,
      capacidadMaximaOficial: 0,
      semanticaCapacidad: 'CONSERVADA_SEGUN_FUENTE; no inferir plazas por bus',
      recorrido: 'INTRA – MOLINO – CENTRO – QUINTA GRANADA – ESPAÑOLITA',
      observacion: 'Código de ruta no vinculado documentalmente a anexo jurídico individual 2026.',
    },
  },
] as const
